FUNCTION YYYYMMDD_TO_JDAY,DATE

;CALL THIS WITH:  RESULT=YYYYMMDD_TO_JDAY(DT)
;   WHERE DT IS THE DATE ARRAY.

;CONVERT DATE ARRAY OF FORM YYYYMMDD TO JULIAN DAY
; ASSUMES ARRAY IS PASSED.

   YYYYMMDD=STRCOMPRESS(DATE,/REMOVE_ALL)
   ;YYYY=STRMID(YYYYMMDD,0,4)
   ;MM=STRMID(YYYYMMDD,4,2)
   ;DD=STRMID(YYYYMMDD,6,2)
   YYYYMMDD=JULDAY(STRMID(YYYYMMDD,4,2),STRMID(YYYYMMDD,6,2), $
                   STRMID(YYYYMMDD,0,4))

   RETURN, YYYYMMDD

END
